
  
name: Deploy using OIDC and SSM

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      S3_BUCKET: amzn-s3bucket-deploytoec2
      INSTANCE_ID: i-09586411125d29d10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Verify Identity
        run: aws sts get-caller-identity

      # Upload static site to S3 
      - name: Upload files to S3 
        run: | 
          aws s3 sync . s3://$S3_BUCKET/ \ 
          --delete \ 



      # Deploy to EC2 via SSM
      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids "$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy static site" \
            --parameters commands='[
              "sudo mkdir -p /usr/share/nginx/html",
              "cd /usr/share/nginx/html",
              "sudo aws s3 sync s3://'$S3_BUCKET'/ . --delete",
              "sudo systemctl restart nginx"
            ]' \
            --region $AWS_REGION
